MyMusicApp/MyMusicApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

admin.site.site_header = "Music Admin"
admin.site.site_title = "Music Admin Portal"
admin.site.index_title = "Welcome To Music Administration Backend"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Music.urls')),
    path('post/', include('blog.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('activate/<slug:uidb64>/<slug:token>)/', user_views.activate_link, name='activate'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyMusicApp/blog/urls.py
from django.urls import path

from . import views
from datetime import date # This to give every create post link a unique url



urlpatterns = [
    path('', views.post_list, name='blog-home'),
    path('user/<str:username>', views.UserPostListView.as_view(), name='user-posts'),
    path('<slug>/', views.post_detail, name='post-detail'),
    path('category/<slug>/', views.category_list, name='category-list'),
    path(f'{date.today()}/new', views.PostCreateView.as_view(), name='post-create'), # Dynamic post create url
    path('post/<slug>/update/', views.PostUpdateView.as_view(), name='post-update'),
    path('post/<slug>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    path('edit_comment/<int:pk>', views.CommentUpdateView.as_view(), name='comment-edit'),
    path('edit_commentreply/<int:pk>', views.CommentReplyUpdateView.as_view(), name='commentreplyedit'),
    path('about/', views.about, name='blog-about'),
    path('commentreplydelete/<int:pk>', views.CommentReplyDelete.as_view(), name='commentreplydelete'),
    path('commentdelete/<int:pk>', views.CommentDelete.as_view(), name='commentdelete'),
    # path('update/<slug>/', views.PostUpdateView.as_view(), name='post-update'),
    # path('delete/<slug>/', views.PostDeleteView.as_view(), name='post-delete'),
    path('post/search/', views.SearchResultsView.as_view(), name='search'),
]

MyMusicApp/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from PIL import Image
from users.models import UserImage


class Hashtag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=100, unique=True, null=True, blank=True)

    def __str__(self):
        return self.name

    def _get_unique_slug(self):
        slug = slugify(self.name)
        unique_slug = slug
        num = 1
        while Hashtag.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)



def image_upload(instance, filename):
    title = instance.title
    slug = slugify(title)
    return "posts/{}/{}".format(slug, filename)


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, unique=True, null=True, blank=True)
    image = models.ImageField(upload_to=image_upload, null=True, blank=True, default='default.jpg')
    image_2 = models.ImageField(upload_to=image_upload, null=True, blank=True)
    category = models.ForeignKey(Hashtag, on_delete=models.CASCADE, null=True, blank=True)
    display_comment = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'slug': self.slug})

    def _get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 900 or img.width > 1200:
            output_size = (900, 1200)
            img.thumbnail(output_size)
            img.save(self.image.path)



class Comment(models.Model):
    blog = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField(max_length=500)
    usrimg = models.ForeignKey(UserImage, on_delete=models.CASCADE, null=True, blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    approved = models.BooleanField(default=True)

    def __str__(self):
        return self.message



class CommentReply(models.Model):
    whichcomment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField(max_length=500)
    blog = models.ForeignKey(Post, on_delete=models.CASCADE)
    usrimg = models.ForeignKey(UserImage, on_delete=models.CASCADE, null=True, blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    approved = models.BooleanField(default=True)

    def __str__(self):
        return self.message

MyMusicApp/blog/forms.py
from .models import Comment, CommentReply, Post
from django.forms import ModelForm, ImageField, FileField
from PIL import Image
from django import forms
from django.core.files.images import get_image_dimensions
from django.core.files import File


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'image', 'date_posted', 'content', 'image_2', 'category', 'display_comment']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['message']


class CommentReplyForm(ModelForm):
    class Meta:
        model = CommentReply
        fields = ['message']

MyMusicApp/blog/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import CommentForm, CommentReplyForm, PostForm
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Post, CommentReply, Comment, UserImage, Hashtag
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.db.models import Q


def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'blog/home.html', context)


# class PostListView(ListView):
#     model = Post
#     template_name = 'blog/home.html'  # <app>/<model>_<viewtype>.html
#     context_object_name = 'posts'
#     ordering = ['-date_posted']
#     paginate_by =


class SearchResultsView(ListView):
    model = Post
    template_name = 'blog/search.html'
    paginate_by = 10

    # def get_queryset(self):
    #     query = self.request.GET.get('q')
    #     object_list = Event.objects.filter(
    #         Q(title__icontains=query) | Q(category__name__icontains=query) |
    #         Q(state__name__icontains=query) | Q(state__name__icontains=query + "state")
    #     )
    #
    #     return ({"object_list": object_list, "query": query})

    def get_context_data(self, **kwargs):
        context = super(SearchResultsView, self).get_context_data(**kwargs)
        query = self.request.GET.get('search')
        object_list = Post.objects.filter(
            Q(title__icontains=query) | Q(category__name__icontains=query) |
            Q(content__icontains=query))

        context.update(
            {"query": query,
             "object_list": object_list,
             }
        )

        return context




def post_list(request):
    posts = Post.objects.all().order_by('-date_posted')
    side_posts = posts[:3]

    context = {
        'posts': posts,
        'side_posts': side_posts
    }
    return render(request, 'blog/home.html', context)


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


# class PostDetailView(DetailView):
#     model = Post

def post_detail(request, slug):
    objects = Post.objects.get(slug=slug)  # Get a specific post based on slug field
    posts = Post.objects.all().order_by('-date_posted') # All Posts
    side_posts = posts[:3] # Posts limited to 3
    com = Comment.objects.filter(blog=objects) # Get comments based on a specific post
    com_count = com.all() # All Comments for the specific Post.. If I was going to
    # place the number of comments in the for loop that loops over all comments,
    # it would have been easy as just {% for comment in com %} {{ comment.message.count }}
    replycom = CommentReply.objects.filter(blog=objects) # comment reply related to a specific Post
    reply_count = replycom.all()
    # replycom2 = CommentReply.objects.filter(blog=objects)
    form1 = CommentForm
    form2 = CommentReplyForm
    category = Hashtag.objects.all()
    com_count2 = com_count.count() # This is only here to show my students how we could do it differently
    related_posts = objects.category.post_set.all().order_by('-date_posted')[:5]



    search_list = ["fuck", "shit", "fucked", "fucking",
                   "mother fucker", "fuckyou", "fuckoff", "fuck-you", "fuck-u", "fuck-off",
                    "fucked", "shit", "asshole", "ass hole", "nigga",
                   "niggro", "ass", "ass-hole", "mother-fucker", "mother -fucker", "-fucker", "--fucker"
                   "---fucker", "-niggaz", "niggas", "niggaz", "bitch", "--bitch", "bitchass",
                   ] # List of words that should not be used whe n making a comment.

    for mess in com_count: # Checks for foul words in comments and deletes any comment found wanting..
        if any(c in mess.message.casefold() for c in search_list):
            mess.delete()
            messages.success(request, f'Your comment was deleted because it contained fowl words or language..')

    for mess in reply_count: # Checks for foul words in comments reply and deletes any comment found wanting..
        if any(c in mess.message.casefold() for c in search_list):
            mess.delete()
            messages.success(request, f'Your comment reply was deleted because it contained fowl words or language..')


    context = {
        'objects': objects,
        'side_posts': side_posts,
        'com': com,
        'replycom': replycom,
        'form1': form1,
        'form2': form2,
        'com_count2': com_count2, # This is only here to show my students how we could do it differently
        'url': "post-detail", # This is to differentiate between messages on post detail page from other pages in the base.html
        'category': category,
        'related_posts': related_posts,
        'reply_count': reply_count

    }
    if request.method == 'POST':

        if request.POST.get('whichcomment'):
            data3 = CommentReplyForm(request.POST) # Assigned CommentReplyForm to data3

            if data3.is_valid(): # if form is valid
                whichcomment = int(request.POST.get('whichcomment'))
                message = data3.cleaned_data['message']
                #                user = User.objects.get(username=request.user.username)
                #                usrimg = UserImage.objects.get(author=user)

                don = data3.save(commit=False)
                don.blog = objects
                don.user = User.objects.get(username=request.user.username)
                don.message = message
                don.whichcomment = Comment.objects.get(id=whichcomment)
                don.usrimg = UserImage.objects.get(author=don.user)
                don.save()

                return HttpResponseRedirect(reverse('post-detail', args=(), kwargs={'slug': slug}))

        else:
            data2 = CommentForm(request.POST)

            if data2.is_valid():
                blog = objects
                message = data2.cleaned_data['message']
                #                usr = User.objects.get(user=request.user.username),
                #                usrimg = UserImage.objects.get(author=usr)

                don = data2.save(commit=False)
                don.blog = objects
                don.user = User.objects.get(username=request.user.username)
                don.message = message
                don.usrimg = UserImage.objects.get(author=don.user)
                don.save()

                '''Comment.objects.create(
                    blog=data1,
                    user= User.objects.get(username=request.user.username),
                    message=message,
                    usrimg=UserImage.objects.get(author=user)

                ).save()'''

                return HttpResponseRedirect(reverse('post-detail', args=(), kwargs={'slug': slug}))

    else:
        return render(request, 'blog/post_detail.html', context)


class PostCreateView(LoginRequiredMixin, CreateView):

    def get(self, request, *args, **kwargs):
        context = {'form': PostForm()}
        return render(request, 'blog/post_create.html', context)

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.author = self.request.user
            post = form.save()
            post.save()
            return HttpResponseRedirect(reverse_lazy('post-detail', args=[post.slug]))
        return render(request, 'blog/post_create.html', {'form': form})


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'image', 'date_posted', 'content', 'image_2', 'category', 'display_comment']
    template_name = "blog/post_update.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

    def get_success_url(self):
        return reverse_lazy('post-detail', kwargs={'slug': self.object.slug})


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/post/'
    template_name = 'blog/post_confirm_delete.html'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})


class CommentReplyDelete(DeleteView):
    model = CommentReply
    template_name = 'blog/comment_delete.html'

    def test_func(self):  #  This adds an extra layer of security. Though we are already checking this in the template,
        # there is nothing like too much security checks.
        comment = self.get_object()
        if self.request.user == comment.user:
            return True
        return False

    def get_success_url(self):
        return reverse_lazy('post-detail', kwargs={'slug': self.object.whichcomment.blog.slug})


class CommentDelete(DeleteView):
    model = Comment
    template_name = 'blog/comment_delete.html'

    def test_func(self):
        comment = self.get_object()
        if self.request.user == comment.user:
            return True
        return False

    def get_success_url(self):
        return reverse_lazy('post-detail', kwargs={'slug': self.object.blog.slug})



class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment

MyMusicApp/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

MyMusicApp/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		 <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

		<title>{{ objects.title }}</title>

		<!-- Google font -->
		<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:700%7CNunito:300,600" rel="stylesheet">

		<!-- Bootstrap -->
		<link type="text/css" rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}"/>

		<!-- Font Awesome Icon -->
		<link rel="stylesheet" href="{% static 'blog/css/font-awesome.min.css' %}">

		<!-- Custom stlylesheet -->
		<link type="text/css" rel="stylesheet" href="{% static 'blog/css/style.css' %}"/>
        <link type="text/css" rel="stylesheet" href="{% static 'users/css/login_controller.css' %}"/>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

    </head>
	<body>

		<!-- Header -->
		<header id="header">
			<!-- Nav -->
			<div id="nav">
				<!-- Main Nav -->
				<div id="nav-fixed">
					<div class="container">
						<!-- logo -->
						<div class="nav-logo">
							<a href="{% url 'blog-home' %}" class="logo"><img src="{% static 'blog/img/logo.png' %}" alt=""></a>
						</div>
						<!-- /logo -->

						<!-- nav -->
						<ul class="nav-menu nav navbar-nav">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'logout' %}">Logout</a></li>
                        {% else %}
							<li><a href="{% url 'login' %}">Login</a></li>
                        {% endif %}
							<li><a href="{% url 'home' %}">Music</a></li>
                            {% if user.is_authenticated %}
							<li class="cat-1"><a href="{% url 'post-create' %}">Create Post</a></li>
                            {% endif %}
							<li class="cat-2"><a href="category.html">JavaScript</a></li>
							<li class="cat-3"><a href="category.html">Css</a></li>
							<li class="cat-4"><a href="category.html">Jquery</a></li>
						</ul>
						<!-- /nav -->

						<!-- search & aside toggle -->
						<div class="nav-btns">
							<button class="aside-btn"><i class="fa fa-bars"></i></button>
							<button class="search-btn"><i class="fa fa-search"></i></button>
                            <form action="{% url 'search' %}" method="get">
							<div class="search-form" >
								<input class="search-input" type="text" name="search" placeholder="Enter Your Search ...">
								<button class="search-close"><i class="fa fa-times"></i></button>
							</div>
                            </form>
						</div>
						<!-- /search & aside toggle -->
					</div>
				</div>
				<!-- /Main Nav -->

				<!-- Aside Nav -->
				<div id="nav-aside">
					<!-- nav -->
					<div class="section-row">
						<ul class="nav-aside-menu">
							<li><a href="{% url 'blog-home' %}">Home</a></li>
                            <li><a href="{% url 'home' %}">Music</a></li>
							<li><a href="about.html">About Us</a></li>
							<li><a href="{% url 'register' %}">Join Us</a></li>
							<li><a href="#">Advertisement</a></li>
							<li><a href="contact.html">Contacts</a></li>
						</ul>
					</div>
					<!-- /nav -->

					<!-- widget posts -->
					<div class="section-row">
						<h3>Recent Posts</h3>
                        {% for post in side_posts %}
						<div class="post post-widget">
							<a class="post-img" href="blog-post.html"><img src="{{ post.image.url }}" alt=""></a>
							<div class="post-body">
								<h3 class="post-title"><a href="blog-post.html">{{ post.title }}</a></h3>
							</div>
						</div>
                                        {% endfor %}

					</div>
					<!-- /widget posts -->

					<!-- social links -->
					<div class="section-row">
						<h3>Follow us</h3>
						<ul class="nav-aside-social">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
						</ul>
					</div>
					<!-- /social links -->

					<!-- aside nav close -->
					<button class="nav-aside-close"><i class="fa fa-times"></i></button>
					<!-- /aside nav close -->
				</div>
				<!-- Aside Nav -->
			</div>
			<!-- /Nav -->

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% for message in messages %}

          {% if url == "post-detail" %}
              <div class="alert alert-{{ message.tags }}" style="color:Red;">
                {{ message }}
              </div>
          {% else %}
              <div class="alert alert-{{ message.tags }}" style="color:Green;">
                {{ message }}
              </div>
                {% endif %}
            {% endfor %}

         </div>
      </div>
    </main>
          {% block content %}{% endblock %}

     <footer id="footer">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-5">
						<div class="footer-widget">
							<div class="footer-logo">
								<a href="{% url 'blog-home' %}" class="logo"><img src="{% static 'blog/img/logo.png' %}" alt=""></a>
							</div>
							<ul class="footer-nav">
								<li><a href="#">Privacy Policy</a></li>
								<li><a href="#">Advertisement</a></li>
							</ul>
							<div class="footer-copyright">
								<span>&copy; <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></span>
							</div>
						</div>
					</div>

					<div class="col-md-4">
						<div class="row">
							<div class="col-md-6">
								<div class="footer-widget">
									<h3 class="footer-title">About Us</h3>
									<ul class="footer-links">
										<li><a href="about.html">About Us</a></li>
										<li><a href="#">Join Us</a></li>
										<li><a href="contact.html">Contacts</a></li>
									</ul>
								</div>
							</div>
							<div class="col-md-6">
								<div class="footer-widget">
									<h3 class="footer-title">Catagories</h3>
									<ul class="footer-links">
										<li><a href="category.html">Web Design</a></li>
										<li><a href="category.html">JavaScript</a></li>
										<li><a href="category.html">Css</a></li>
										<li><a href="category.html">Jquery</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>

					<div class="col-md-3">
						<div class="footer-widget">
							<h3 class="footer-title">Join our Newsletter</h3>
							<div class="footer-newsletter">
								<form>
									<input class="input" type="email" name="newsletter" placeholder="Enter your email">
									<button class="newsletter-btn"><i class="fa fa-paper-plane"></i></button>
								</form>
							</div>
							<ul class="footer-social">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
								<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
							</ul>
						</div>
					</div>

				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</footer>
		<!-- /Footer -->

		<!-- jQuery Plugins -->
		<script src="{% static 'blog/js/jquery.min.js' %}"></script>
		<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
		<script src="{% static 'blog/js/main.js' %}"></script>
        <script src="{% static 'blog/js/books.js' %}"></script>
	</body>
</html>

MyMusicApp/blog/templates/blog/category_list.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}

	</header>
    	<!-- section -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- post -->

					<!-- /post -->

					<!-- post -->

					<!-- /post -->
				</div>
				<!-- /row -->

				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<div class="section-title">
							<h2 style="text-align: center">Posts About {{ post.name }}</h2>
						</div>
					</div>

					<!-- post -->{% for post in posts %}
					<div class="col-md-4">
						<div class="post">
							<a class="post-img" href="{% url 'post-detail' post.slug %}"><img src="{{ post.image.url }}" alt=""></a>
							<div class="post-body">
								<div class="post-meta">
									<a class="post-category cat-{{ post.category.id }}" href="">{{ post.category }}</a>
									<span class="post-date">{{ post.date_posted }}</span>
								</div>
								<h3 class="post-title"><a href="{% url 'post-detail' post.slug %}">{{ post.title }}</a></h3>
							</div>
						</div>
					</div>
					<!-- /post -->{%  endfor %}
</div>
            </div>
        </div>
            {% endblock content %}

MyMusicApp/blog/templates/blog/partial_comment_list.html
						<div class="section-row">
							<div class="section-title">
								{% if objects.comment_set.all.count > 1 %}<h2> {{ objects.comment_set.all.count }} Comments</h2> {% elif objects.comment_set.all.count == 1 %} <h2> {{ objects.comment_set.all.count }} Comment</h2> {% else %} <h2> Be the first to comment.. </h2> {% endif %}
							</div>

							<div class="post-comments">
								<!-- comment -->{% for comment in com %}
                                {% if comment.approved %}
								<div class="media">
									<div class="media-left">
										<img class="media-object" src="{{ comment.usrimg.myimage.url }}" alt="">
									</div>
									<div class="media-body">
										<div class="media-heading">
											<h4>{{ comment.user }}</h4>
                                            <span class="time">{{ comment.date_posted }}</span>
                                              <span style="font-style: italic">{% if comment.commentreply_set.count > 1 %}  {{ comment.commentreply_set.count }} Replies.. {% elif comment.commentreply_set.count == 1 %} {{ comment.commentreply_set.count }} Reply.. {% elif comment.commentreply_set.count < 1 %} {% endif %}</span>
{#											        <div class="replybutton" style="">#}


										</div>
                                        <p>{{ comment.message }}</p>
                  {% if comment.user == request.user %}<a href="{% url 'commentdelete' comment.pk %}" class="small"><span class="badge badge-primary">Delete Comment</span></a>
                                    <a href="{% url 'comment-edit' comment.pk %}" class="small"><span class="badge badge-primary">Edit Comment</span></a>{% endif %}
{#                                     <div class="replybutton" style="">#}
{#                                    <div class="replybutton" style="">#}
{#                                        <span class="text-right small"> Reply</span>#}

{##}
{#    <div class="row replybox" style="display: none">#}
{#        <div class="col-sm-12 ml-5 pl-5">#}


   <style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

/* Button used to open the chat form - fixed at the bottom of the page */
.open-button {
  color: white;
}
/* The popup chat - hidden by default */
.myForm {
  display: none;
}
/* Add some hover effects to buttons */
.form-container .btn:hover, .open-button:hover {
  opacity: 1;
}
</style>
           {% if user.is_authenticated %}
    <button class="open-button openForm">Reply</button>
            <form method='POST' class="myForm mt-5">
                {% csrf_token %}
                <input type="hidden" name='whichcomment' id='id_whichcomment' value="{{comment.id}}">
                <input class="" type="text" name='message' maxlength="250" id="id_message" placeholder="Reply. . . " required>
                <button style="padding:1%;" class="btn" type="submit">submit</button>
                <button class="btn cancel closeForm">Close</button>
            </form>
           {% endif %}


                                    <!-- comment -->{% for r in replycom %}
                                    {% if r.approved == True %}
                                    {% if r.whichcomment.message == comment.message %}
                                    <div class="media">
                                        <div class="media-left">
                                            <img class="media-object" src="{{ r.usrimg.myimage.url }}" alt="">
                                        </div>
                                        <div class="media-body">
                                            <div class="media-heading">
                                                <h4>{{ r.user }}</h4>
                                                <span class="time">{{ r.date_posted }}</span>
                    {#													<a href="#" class="reply">Reply</a>#}
                                            </div>
                                            <p>{{ r.message }}</p>
                                            {% if r.user == request.user %}<a href="{% url 'commentreplydelete' r.pk %}" class="small"><span class="badge badge-primary">delete</span></a>
                                            <a href="{% url 'commentreplyedit' r.pk %}" class="small"><span class="badge badge-primary">Edit Reply</span></a>{% endif %}

                                        </div>
                                    </div>{% endif %}{% endif %}{% endfor %}
                                    <!-- /comment -->
                                </div>
                            </div>{% endif %}{% endfor %}
                            <!-- /comment -->

                        </div>
                    </div>